#!/bin/bash

if [ "$ANTHROPIC_API_KEY" = "" ]; then
	>&2 echo "Please export your ANTHROPIC_API_KEY."
	>&2 echo 'For example: `export ANTHROPIC_API_KEY="sk-ant-api03-JZ..."`'
	exit 1
fi

if [ $# -ne 1 ]; then
	>&2 echo "Please run this program with the specified command parameter."
	>&2 echo 'For example: `cat my-text | '$0' "Translate to Korean."`'
	exit 1
fi

JSON="$(mktemp)"

COMMAND=$1
[ ${#COMMAND} -eq 2 ] && COMMAND="Translate to $1 without comment."

curl https://api.anthropic.com/v1/messages \
	--silent \
	--header "x-api-key: $ANTHROPIC_API_KEY" \
	--header "anthropic-version: 2023-06-01" \
	--header "content-type: application/json" \
	--data "$(jq -Rs '{ model: "claude-3-opus-20240229", max_tokens: 1024, messages: [ {role: "user", content: . } ] }' | sed -e "s/\"content\": \"/\"content\": \"$COMMAND: /")" \
	> "$JSON"

if [ $? -ne 0 ]; then
	rm "$JSON"
	exit 1
fi

if ! cat $JSON | jq -r '.content[] | .text' 2> /dev/null; then
	>&2 echo "Server terminated for the following reason: $(cat $JSON | jq -r '.error | .type' 2> /dev/null)"
	rm "$JSON"
	exit 1
fi

rm "$JSON"
