#!/bin/bash

if [ "$ANTHROPIC_API_KEY" = "" ]; then
	echo "Please export your ANTHROPIC_API_KEY."
	echo 'For example: `export ANTHROPIC_API_KEY="sk-ant-api03-JZkHG..."`'
	exit 1
fi

if [ $# -ne 1 ]; then
	echo "Please run this program with the specified command parameter."
	echo 'For example: `cat my-text | '$0' "Translate to Korean."`'
	exit 1
fi

curl https://api.anthropic.com/v1/messages \
	-s \
	--header "x-api-key: $ANTHROPIC_API_KEY" \
	--header "anthropic-version: 2023-06-01" \
	--header "content-type: application/json" \
	--data \
"$(jq -Rs '{ model: "claude-3-opus-20240229", max_tokens: 1024, messages: [ {role: "user", content: . } ] }' | sed -e "s/\"content\": \"/\"content\": \"$1: /")" | jq -r '.content[] | .text'
