#!/bin/bash

if [ "$DEEPL_API_KEY" = "" ]; then
	>&2 echo "Please export your DEEPL_API_KEY."
	>&2 echo 'For example: `export DEEPL_API_KEY="d400341c-e4..."`'
	exit 1
fi

if [ $# -ne 1 ]; then
	>&2 echo "Please run this program with the target language."
	>&2 echo 'For example: `'$0' KO < my-text` or `cat my-text | '$0' EN`'
	exit 1
fi

JSON="$(mktemp)"

curl -X POST "https://api-free.deepl.com/v2/translate" \
	--silent \
	--header "Authorization: DeepL-Auth-Key $DEEPL_API_KEY" \
	--header "Content-Type: application/json" \
	--data "$(jq -Rs '{ "text": [ . ], "target_lang": '\"$1\"' }')" \
	> "$JSON"

if [ $? -ne 0 ]; then
	rm "$JSON"
	exit 1
fi

if ! cat "$JSON" | jq --exit-status -r '.translations[0].text // empty' 2>/dev/null; then
	>&2 echo "Server terminated for the following reason: $(cat $JSON | jq -r '.message' 2> /dev/null)"
	rm "$JSON"
	exit 1
fi

rm "$JSON"
