#!/bin/bash

if [ "$GEMINI_API_KEY" = "" ]; then
	>&2 echo "Please export your GEMINI_API_KEY."
	>&2 echo 'For example: `export GEMINI_API_KEY="AIzaSyBLyhX_prFkFb..."`'
	exit 1
fi

if [ $# -ne 1 ]; then
	>&2 echo "Please run this program with the specified command."
	>&2 echo 'For example: `cat my-text | '$0' "Translate to Korean"`'
	exit 1
fi

JSON="$(mktemp)"

COMMAND=$1
[ ${#COMMAND} -eq 2 ] && COMMAND="Translate to $1 without comment."

curl \
	-s \
	-H 'Content-Type: application/json' \
	-X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=$GEMINI_API_KEY" \
	-d "$(jq -Rs '{"contents":[{"parts":[{"text": . }]}]}' | sed -e "s/\"text\": \"/\"text\": \"$COMMAND:\n/")" \
	> "$JSON"

if [ $? -ne 0 ]; then
	rm "$JSON"
	exit 1
fi

REASON="$(cat $JSON | jq -r '.candidates[].finishReason' 2> /dev/null)"
if ! [ "$REASON" = "" ]; then
	if ! cat $JSON | jq -r '.candidates[].content.parts[].text' 2> /dev/null; then
		>&2 echo "Server terminated for the following reason: $REASON"
		rm "$JSON"
		exit 1
	fi
else
	>&2 echo "Server terminated for an unknowing reason."
	rm "$JSON"
	exit 1
fi

rm "$JSON"
